PREFIX ?= /usr/local
BIN := .build/release/am
VERSION_FILE := Sources/am/Version.generated.swift

# FoundationModels module version from the current SDK (the runtime API exposes
# no model/version, so this is the closest build-time proxy).
SDK_VERSION := $(shell grep -hoE 'user-module-version [0-9.]+' \
  "$$(xcrun --show-sdk-path)/System/Library/Frameworks/FoundationModels.framework/Versions/A/Modules/FoundationModels.swiftmodule"/*.swiftinterface \
  2>/dev/null | head -1 | awk '{print $$2}')

.PHONY: build install uninstall clean test version

# Regenerate the SDK-version constant only when it actually changes, so we don't
# dirty the tree or force a needless rebuild.
version:
	@test -n "$(SDK_VERSION)" || { echo "am: could not read FoundationModels SDK version"; exit 1; }
	@printf '// Generated by `make` (target: version) from the FoundationModels SDK module\n// version. Committed so plain `swift build` / brew builds compile without make;\n// `make` overwrites it with the building machine'\''s SDK version. Do not edit.\nlet FM_SDK_VERSION = "%s"\n' "$(SDK_VERSION)" > "$(VERSION_FILE).tmp"
	@if cmp -s "$(VERSION_FILE).tmp" "$(VERSION_FILE)"; then rm -f "$(VERSION_FILE).tmp"; \
	else mv "$(VERSION_FILE).tmp" "$(VERSION_FILE)"; echo "am: FM_SDK_VERSION = $(SDK_VERSION)"; fi

build: version
	swift build -c release

install: build
	install -d "$(PREFIX)/bin"
	install "$(BIN)" "$(PREFIX)/bin/am"

uninstall:
	rm -f "$(PREFIX)/bin/am"

clean:
	swift package clean
	rm -rf .build

test: build
	$(BIN) check
