// Generated by `make` (target: version) from the FoundationModels SDK module
// version. Committed so plain `swift build` / brew builds compile without make;
// `make` overwrites it with the building machine's SDK version. Do not edit.
let FM_SDK_VERSION = "1.5.2"
